import { defineConfig } from 'tsup';

export default defineConfig([
  // ESM build
  {
    entry: {
      'stera-icons': 'src/index.ts',
      'base': 'src/base.ts',
      'dynamic': 'src/dynamic.ts',
      'dynamic-variants': 'src/dynamic-variants.ts',
    },
    format: ['esm'],
    dts: false, // Disabled - declarations generated by scripts/generate-declarations.js for better memory efficiency
    splitting: false,
    sourcemap: true,
    clean: false, // Don't clean dist to preserve metadata files
    external: ['react'],
    treeshake: true,
    minify: true,
    outDir: 'dist/esm',
    outExtension() {
      return {
        js: '.js',
      };
    },
  },
  // CJS build
  {
    entry: {
      'stera-icons': 'src/index.ts',
      'base': 'src/base.ts',
      'dynamic': 'src/dynamic.ts',
      'dynamic-variants': 'src/dynamic-variants.ts',
    },
    format: ['cjs'],
    dts: false, // Disabled - declarations generated by scripts/generate-declarations.js for better memory efficiency
    splitting: false,
    sourcemap: true,
    clean: false, // Don't clean dist to preserve metadata files
    external: ['react'],
    treeshake: true,
    minify: true,
    outDir: 'dist/cjs',
    outExtension() {
      return {
        js: '.js',
      };
    },
    esbuildOptions: (options) => {
      options.banner = {
        js: '"use strict";',
      };
    },
  },
]);
